### ISSUE TITLE
Join ImageNoise?

### ISSUE THREAD

**Issue by johnnychen94** [roflmaostc/Noise.jl#3]
ImageNoise.jl is my small playground for denoise algorithms; I don't have spent much time on adding different noises, which Noise.jl seems to have done pretty well. If you like, I can move it under JuliaImages and we can work on it together.

**Comment by roflmaostc** [comment]
I also found your package when I was working on my code back then. 
Noise.jl was also my first Julia project so it was also a learning experience for me...
I somehow stopped developing it because I needed no more functionality.

So far I only wanted to apply noise to N dimensional images/arrays because I couldn't find a package for applying Poisson shot noise. I think I also would only contribute to adding Noise. Denoising (in my case microscopy) will be handled implicitly by [DeconvOptim.jl](www.github.com/roflmaostc/DeconvOptim.jl) which is under development but will be released in a few weeks.
Apart from what I've done in DeconvOptim.jl I don't have sophisticated experience in denoising.

But yeah, we could join our efforts and primarily use your code. Your design seems to be more complicated but on the other hand quite smart. I then could incorporate Poisson noise into your code if you want to. Once I understood your pipeline, we could also add the other ones of my package.

Does that sound acceptable?

**Comment by roflmaostc** [comment]
Ah, should we change the Name to "Noise.jl"?
If we are using arrays then "Image" implies a restriction which is not there.
Haha, but then I'm not sure if "JuliaImages" would be the right place :joy:

**Comment by johnnychen94** [comment]
Perhaps the important thing does not matter how many algorithms or noise types you or me add to it, but instead we join our efforts and so that other people won't try to re-invent it. These are not very difficult things to do, so we might need some effort to make it standardized.

I didn't realize that there are people out there using Julia to do noise things so I didn't spend much time on polishing my little ImageNoise.jl project, but since at least you're using it I guess there's a need to do it.

> I think I also would only contribute to adding Noise.

This seems totally fine to me. After all, we're doing our own research work, which happens to benefit others.

> Ah, should we change the Name to "Noise.jl"? If we are using arrays then "Image" implies a restriction which is not there.

I'd prefer to still keep the "ImageNoise.jl", as far as I know, there isn't a better organization for it. Almost all packages under JuliaImages actually works on plain numeric array due to the fantastic design on colorant types.

The name `Noise.jl` doesn't indicate its support for `Colorant` types 😆 . We could possible split it into `Noise.jl` for numerical array and `ImageNoise.jl` for Colorant array, but by doing this we're adding more maintenance burden.

**Comment by johnnychen94** [comment]
Invitation sent.
